/*
 atvise webMI http://www.atvise.com/

 Copyright (C) 2008-2013 Certec EDV GmbH. All Rights Reserved.
 Copyright (C) 2003-2005 Tom Wu. All Rights Reserved.
 Copyright (C) 1998-2009, Paul Johnston & Contributors. All Rights Reserved.
 $Id: dc4b7b185d92d46db98fc2bc48518dfcfda12ede $

 WARNING: This software program is protected by copyright law
 and international treaties. Unauthorized reproduction or
 distribution of this program, or any portion of it, may result
 in severe civil and criminal penalties, and will be prosecuted
 to the maximum extent possible under the law.

 May only be used with explicit written authorization by Certec
*/
function o(fa){throw fa;}var r=!0,s=null,F=!1;function H(){return function(){}}
(function(){try{return(this.ed=parent&&parent.webMI?parent.webMI:opener&&opener.webMI?opener.webMI:top&&top.webMI?top.webMI:s).proxy(s,window)}catch(fa){return r}})()&&(window.webMI=function(){function fa(a,b){b.location.href=a}function z(a){return"undefined"===typeof a}function ga(a){return"number"===typeof a}function t(a){return"string"===typeof a}function y(a){return"object"===typeof a}function C(a){return"function"===typeof a||a!==s&&y(a)&&"call"in a}function v(a){try{return y(a)&&a.constructor&&
-1!=a.constructor.toString().indexOf("Array")}catch(b){return F}}function ha(a){if(!y(a))return F;for(var b in a)return F;return r}function I(a,b){console.error("Exception @ "+a+": "+b.message)}function ya(a,b){try{return a.contentDocument==b||a.contentWindow&&a.contentWindow.document==b}catch(c){return F}}function za(a,b){try{return"getContentDocument"in a&&a.getContentDocument()==b}catch(c){I("getContentDocument",c)}}function A(a,b){return!y(a)?F:String(a.nodeName).toLowerCase()==b}function N(){o("Invalid Argument")}
function ia(a){return function(b){try{b()}catch(c){I(a,c)}}}function G(a,b,c){y(a)||o("Can't add event '"+b+"' to non-object ("+String(c)+")");try{a.addEventListener(b,c,F)}catch(d){try{a.attachEvent("on"+b,c)}catch(e){var f=H();a&&a["on"+b]&&(f=a["on"+b]);a["on"+b]=function(a){f(a);c(a)}}}$&&("change"==b&&A(a,"input"))&&G(a,"keydown",function(a){13==a.keyCode&&c(a)})}function Wa(a){return function c(d,e,f){if(d!==s){if(v(d))return l(d,function(a){return c(a,e,f)});if(t(d)){var g=d;(d=a(g))||o("Can't find element '"+
g+"'.")}if(!v(e))return G(d,e,f);l(e,function(a){G(d,a,f)})}}}function Xa(a,b,c){return function(d,e){d in Aa||N();var f=Aa[d];return f[1].call(f[0],aa(f[2],e),a,b,c,b)}}function l(a,b){for(var c=0;c<a.length;++c)b(a[c],c)}function n(a,b){for(var c in a)b(a[c],c)}function pa(a,b){for(var c=0;c<a.length;++c)b(a[c],c)&&a.splice(c--,1)}function S(a,b){var c=F;b!=s&&l(b,function(b){b==a&&(c=r)});return c}function aa(a,b){function c(){}c.prototype=a;var d=new c;if($)try{n(a,function(a,b){d[b]!=a&&(d[b]=
a)})}catch(e){}n(b,function(a,b){d[b]=a});return d}function B(a,b){n(b,function(b,d){a.prototype[d]=b})}function Ya(a,b,c,d,e){function f(g){g=Ya(a,b,c,parseInt(d.substr(g,2),16),parseInt(e.substr(g,2),16));g-=g%1;return(16>g?"0":"")+g.toString(16)}function g(a){return!t(a)||4!=a.length||"#"!=a.charAt(0)?a:"#"+a.charAt(1)+a.charAt(1)+a.charAt(2)+a.charAt(2)+a.charAt(3)+a.charAt(3)}d=g(d);e=g(e);return t(d)&&7==d.length&&t(e)&&7==e.length?"#"+f(1)+f(3)+f(5):d+(e-d)*(a-b)/(c-b)}function Ba(a){function b(a,
b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535}function c(a,c,d,e,g,f){a=b(b(c,a),b(e,f));return b(a<<g|a>>>32-g,d)}function d(a,b,d,e,g,f,q){return c(b&d|~b&e,a,b,g,f,q)}function e(a,b,d,e,g,f,q){return c(b&e|d&~e,a,b,g,f,q)}function f(a,b,d,e,g,f,q){return c(d^(b|~e),a,b,g,f,q)}for(var g=1732584193,h=-271733879,i=-1732584194,j=271733878,k=[],u=8*a.length,m=0;m<u;m+=8)k[m>>5]|=(a.charCodeAt(m/8)&255)<<m%32;k[u>>5]|=128<<u%32;k[(u+64>>>9<<4)+14]=u;for(m=0;m<k.length;m+=16)var a=
g,u=h,w=i,q=j,g=d(g,h,i,j,k[m+0],7,-680876936),j=d(j,g,h,i,k[m+1],12,-389564586),i=d(i,j,g,h,k[m+2],17,606105819),h=d(h,i,j,g,k[m+3],22,-1044525330),g=d(g,h,i,j,k[m+4],7,-176418897),j=d(j,g,h,i,k[m+5],12,1200080426),i=d(i,j,g,h,k[m+6],17,-1473231341),h=d(h,i,j,g,k[m+7],22,-45705983),g=d(g,h,i,j,k[m+8],7,1770035416),j=d(j,g,h,i,k[m+9],12,-1958414417),i=d(i,j,g,h,k[m+10],17,-42063),h=d(h,i,j,g,k[m+11],22,-1990404162),g=d(g,h,i,j,k[m+12],7,1804603682),j=d(j,g,h,i,k[m+13],12,-40341101),i=d(i,j,g,h,k[m+
14],17,-1502002290),h=d(h,i,j,g,k[m+15],22,1236535329),g=e(g,h,i,j,k[m+1],5,-165796510),j=e(j,g,h,i,k[m+6],9,-1069501632),i=e(i,j,g,h,k[m+11],14,643717713),h=e(h,i,j,g,k[m+0],20,-373897302),g=e(g,h,i,j,k[m+5],5,-701558691),j=e(j,g,h,i,k[m+10],9,38016083),i=e(i,j,g,h,k[m+15],14,-660478335),h=e(h,i,j,g,k[m+4],20,-405537848),g=e(g,h,i,j,k[m+9],5,568446438),j=e(j,g,h,i,k[m+14],9,-1019803690),i=e(i,j,g,h,k[m+3],14,-187363961),h=e(h,i,j,g,k[m+8],20,1163531501),g=e(g,h,i,j,k[m+13],5,-1444681467),j=e(j,g,
h,i,k[m+2],9,-51403784),i=e(i,j,g,h,k[m+7],14,1735328473),h=e(h,i,j,g,k[m+12],20,-1926607734),g=c(h^i^j,g,h,k[m+5],4,-378558),j=c(g^h^i,j,g,k[m+8],11,-2022574463),i=c(j^g^h,i,j,k[m+11],16,1839030562),h=c(i^j^g,h,i,k[m+14],23,-35309556),g=c(h^i^j,g,h,k[m+1],4,-1530992060),j=c(g^h^i,j,g,k[m+4],11,1272893353),i=c(j^g^h,i,j,k[m+7],16,-155497632),h=c(i^j^g,h,i,k[m+10],23,-1094730640),g=c(h^i^j,g,h,k[m+13],4,681279174),j=c(g^h^i,j,g,k[m+0],11,-358537222),i=c(j^g^h,i,j,k[m+3],16,-722521979),h=c(i^j^g,h,
i,k[m+6],23,76029189),g=c(h^i^j,g,h,k[m+9],4,-640364487),j=c(g^h^i,j,g,k[m+12],11,-421815835),i=c(j^g^h,i,j,k[m+15],16,530742520),h=c(i^j^g,h,i,k[m+2],23,-995338651),g=f(g,h,i,j,k[m+0],6,-198630844),j=f(j,g,h,i,k[m+7],10,1126891415),i=f(i,j,g,h,k[m+14],15,-1416354905),h=f(h,i,j,g,k[m+5],21,-57434055),g=f(g,h,i,j,k[m+12],6,1700485571),j=f(j,g,h,i,k[m+3],10,-1894986606),i=f(i,j,g,h,k[m+10],15,-1051523),h=f(h,i,j,g,k[m+1],21,-2054922799),g=f(g,h,i,j,k[m+8],6,1873313359),j=f(j,g,h,i,k[m+15],10,-30611744),
i=f(i,j,g,h,k[m+6],15,-1560198380),h=f(h,i,j,g,k[m+13],21,1309151649),g=f(g,h,i,j,k[m+4],6,-145523070),j=f(j,g,h,i,k[m+11],10,-1120210379),i=f(i,j,g,h,k[m+2],15,718787259),h=f(h,i,j,g,k[m+9],21,-343485551),g=b(g,a),h=b(h,u),i=b(i,w),j=b(j,q);g=[g,h,i,j];h="";for(m=0;m<4*g.length;++m)h+=x.charAt(g[m>>2]>>8*(m%4)+4&15)+x.charAt(g[m>>2]>>8*(m%4)&15);return h}function Za(a,b){if(!t(a))return"";var c=[],d=/(%(%|((\d+)\$|\((\w+)\))?(\-)?(\+|\x20)?(0)?(\d+)?(\.(\d+))?([bcdeEfFgGosxX]))?)/g,e=[],f=0,g=1;
if(zb){for(var h=0,i,j;i=d.exec(a);)j=i.index+i[0].length,j>h&&(e.push(a.slice(h,i.index)),!z(/()??/.exec("")[1])&&1<i.length&&i[0].replace(RegExp("^"+d.source+"$(?!\\s)","g"),function(){for(var a=1;a<arguments.length-2;++a)arguments[a]||(i[a]=void 0)}),l(i,function(a,b){b&&e.push(a)}),h=j),d.lastIndex===i.index&&d.lastIndex++;e.push(h==a.length?"":a.slice(h))}else e=a.split(d);for(;;){c.push(e[f++]);if(f>=e.length)break;var d=0,k=parseInt(e[f+3],10)||g++,h=!e[f+5];j=e[f+7]||" ";var u="",m=parseInt(e[f+
8],10),w=parseInt(e[f+10],10);isNaN(w)&&(w=6);for(var q=e[f+11],k=arguments[k],J=e[f+4],D=0;D<arguments.length;++D)if(y(arguments[D])&&J in arguments[D]){k=arguments[D][J];break}var D=String(k),n=Math.abs(parseInt(k,10)),K=p(k),J=0>K?"-":e[f+6]?"+":"",K=Math.abs(K);""!=q&&z(k)&&("%"==e[f+1]?q=e[f+1]:N());if("%"==q)k=q;else if("b"==q)k=n.toString(2);else if("c"==q)k=String.fromCharCode(n);else if("d"==q)k=n;else if("e"==q||"E"==q){for(;10<K;)K/=10,++d;for(;K&&1>K;)K*=10,--d;k=Za("%."+w+"f%s%02d",K.toFixed(w),
q+(0>d?"-":"+"),Math.abs(d))}else"f"==q?k=K.toFixed(w):"o"==q?k=n.toString(8):"s"==q?k=m?D.substring(0,m):D:"x"==q||"X"==q?(k=n.toString(16),"X"==q&&(k=k.toUpperCase())):(k=e[f+1],--g);k=String(k);for(D=0;D<m-k.length-J.length;++D)u+=j;k=h?"0"==j?J+u+k:u+J+k:J+k+u;c.push(k);f+=12}return c.join("")}function ba(){this.a=this.d=1;this.b=this.c=this.e=this.f=0}function $a(a,b){6==b.length&&(a.a=p(b[0]),a.b=p(b[1]),a.c=p(b[2]),a.d=p(b[3]),a.e=p(b[4]),a.f=p(b[5]));return a}function Ca(){this.x=this.y=0}
function ab(a){$&&9>$&&(a.XMLHttpRequest=function(){var a;l(["Msxml2.XMLHTTP.6.0","Msxml2.XMLHTTP.3.0","Msxml2.XMLHTTP","Microsoft.XMLHTTP"],function(b){try{a=a||new ActiveXObject(b)}catch(e){}});if(a)return a;o("This browser does not support XMLHttpRequest.")});z(a.JSON)&&(a.JSON={parse:function(a){var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;b.lastIndex=0;b.test(a)&&(a=a.replace(b,function(a){return"\\u"+("0000"+(+a.charCodeAt(0)).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return eval("("+a+")");o(new SyntaxError("JSON.parse"))},stringify:function(b){if(v(b)){var d=[];l(b,function(b){d.push(a.JSON.stringify(b))});return"["+d.join(",")+"]"}if(b!==s&&y(b))return d=[],n(b,function(b,c){d.push(a.JSON.stringify(c)+":"+a.JSON.stringify(b))}),"{"+d.join(",")+"}";t(b)&&(b='"'+b+'"');
return String(b)}});z(a.console)&&(a.console={});var b="log"in a.console?a.console.log:a.console.log=H();C(a.console.info)||(a.console.info=function(a){b("I: "+a)});C(a.console.warn)||(a.console.warn=function(a){b("W: "+a)});C(a.console.error)||(a.console.error=function(a){b("E: "+a)})}function Da(){for(var a in T)for(var b=0;b<T[a].length;++b)if(T[a][b].Fc(Da))return;setTimeout(Da,50)}function ca(a){a in T||(T[a]=[]);return T[a]}function qa(a){var b=a.indexOf("/");return 0>b?"":ja===s||a.substr(0,
b)==ja?"":a.substr(0,b)}function ra(a){var b=a.indexOf("/");return 0>b?a:a.substr(b+1)}function da(a,b,c){var d={},e=1;n(b,function(b,g){l(ca(g),function(h){++e;h.m(a,3,b,h.ca()?function(a){d[g]=a;--e||c(d)}:H())})});--e||c(d)}function bb(a,b,c){var d=[],e=[];n(b,function(a,b){d.push("address[]="+encodeURIComponent(b));e.push(a)});l(ca(a),function(a){a.ca()&&a.m("read",3,d,function(a){l(a.result,function(a,b){l(e[b],function(b){b.N(a,b.key)})});c()})})}function cb(){n(E,function(a){l(a.data.Lb,function(a){try{a(-1)}catch(c){}})})}
function db(a,b,c){var d=this;d.s=b;d.pa=a;d.Ga=c?"":b;d.zc=c?"":', servername="'+b+'"';d.I=1;d.Ka=F;d.Zc=F;d.la={};d.U={};d.V={};d.Ea=[];if(c)d.m(c[1].toLowerCase(),1,s,function(b){var f=c[0].indexOf("G"),g=c[0].indexOf("W"),h=b.result,i=h.substr(f,g),j=[function(a,b,c,d){a[b]=c|d},function(a,b,c,d){a[b]=c>d?c:d},function(a,b,c,d){a[b]=d?c/d:0},function(a,b,c,d){a[b]=c<d?c:d},function(a,b,c,d){a[b]=c-d},function(a,b,c,d){a[b]=c<<(d&7)|c>>8-(d&7)},function(a,b,c,d){a[b]=c*d},function(a,b,c,d,e,g){a[b]=
c;a[e]=d;a[g]=a[b]},function(a,b,c,d){a[b]=d?c%d:0},function(a,b,c,d){a[b]=c>>(d&7)|c<<8-(d&7)},function(a,b,c,d){a[b]=c&d},function(a,b,c,d){a[b]=(c+d)/2},function(a,b,c,d){a[b]=c+d},function(a,b,c,d){a[b]=c^~d},function(a,b,c,d){a[b]=c^d},function(a,b,c,d){for(var e=0,b=0;8>b;++b)e+=(c>>b&1)+(d>>b&1);a[b]=e}];l(U,function(a){a(h)});U=h;h=Ba(i);a.p=U.lastIndexOf(h.substr(f,f));a.p-=U.indexOf(h.substr(U==h,f));a.p=a.p==g+f;a.p?d.m(c[1].toLowerCase(),1,c[2].substr(0,37).replace(/\+/,"="),function(b){for(var c=
[[],[]],e=[],g=[],q=0;q<i.length;++q)c[q%2].push(x.indexOf(i.charAt(q))),e.push(x.indexOf(x.charAt(79+q))),g.push(x.indexOf(b.result.toUpperCase().charAt(q))),a.p=!a.p;for(q=0;q<f;++q)e[q]=e[2*q]<<4|e[2*q+1],g[q]=g[2*q]<<4|g[2*q+1];for(q=0;q<f/2;++q)j[c[0][q]](e,c[1][q],e[c[1][q+8]]&255,e[c[0][q+8]]&255,c[1][q+8],c[0][q+8],e.pop(),e.pop());l(e,function(b,c){a.p&=(b&255)==g[c]});d.$(1)}):d.$(1)});else{d.s="";for(b=0;64>b;++b)d.s+=x.charAt(64*Math.random())}d.m("info",1,s,function(b){c&&(a.bb=b);d.bb=
b;var f=b.features;if(!("features"in b)){var g=b.certificationlevel,f=b.features=["read","write"];b.securitysupport&&f.push("login","changepassword");"basic"!=g&&(f.push("session","subscribedata"),"advanced"!=g&&(f.push("queryfilter","subscribefilter"),"scada"!=g&&f.push("multipoint")))}c&&(b=S("multipoint",f)?b.servername:s,""==b&&o("Invalid servername"),ja!==b&&(""==ja&&(Q.Bb(b),V.Bb(b)),ja=b));d.I=S("session",f)?5:S("processimage",f)?3:2;d.na=Q.Ja(d.Ga,d);d.ha=V.Ja(d.Ga,d);if(5==d.I){var h=a.vb(d.s);
""!=h&&(h="cipher="+h);return d.m("createsession",1,h,function(b){d.K=b.sessionid;if(c)a.K=d.K;d.I=6;d.m("createsubscription",1,s,function(a){d.cb=a.subscriptionid;console.info("Created session '"+d.K+"' with main subscription '"+d.cb+"'"+(d.Ga?" @ '"+d.Ga+"'":""));d.I=7;eb||Da();eb=r;d.$(1)})})}L["data.publishinterval"]||(L["data.publishinterval"]=250);3==d.I&&d.m("listprocessimage",1,h,function(a){d.Mc=a.result;d.Pb=[];l(d.Mc,function(a){d.Pb.push(a.address)});d.I=4;d.$(1)})})}function fb(a){this.s=
"";this.Yc=a;a=[0,3,4,19,23,26];x=x.slice(a[0],x.length-a.length);for(var b=1;b<a.length;++b)x+=x.charAt(32+a[2]+a[b%2?b:0]);this.Z=x.indexOf("/");this.p=s;this.Rc={};this.Na=r;for(a=0;a<=this.Z;++a)this.s+=x.charAt(this.Z*Math.random()),x+=x.charAt(16*(1-Math.random()));this.Z=1;this.qc("",this.s,x.split("/"))}function gb(a,b){this.ja=a;this.dd=b;this.u={};this.T={};this.Qb=ca(b)}function Ea(a){this.ja=a;this.J={}}function hb(a){this.k=a}function ib(a){this.k=a;this.V=[];this.Hb=[];this.Kb=[];this.Lb=
[]}function sa(a){if(v(a)){var b=[];l(a,function(a){b.push(sa(a))});return"["+b.join(",")+"]"}return encodeURIComponent(a)}function Fa(a){y(a)||N();var b=[];n(a,function(a,d){v(a)?l(a,function(a){b.push(encodeURIComponent(d)+"[]="+sa(a))}):b.push(encodeURIComponent(d)+"="+sa(a))});return b}function jb(a,b,c){l(a,function(a){if(z(a.A)||a.A==b||v(a.A)&&S(b,a.A))try{a.S(c)}catch(e){}})}function Ab(a){var b=a.keyCode,c=0;a.Ic&&(c+=a.Ic);a.altKey&&(c+=1);a.ctrlKey&&(c+=2);a.shiftKey&&(c+=4);a.metaKey&&
(c+=8);jb(Ga,b,a);ka[b]=1;l(Ha,function(d){if(d.Jc==c&&d.A==b)try{d.S(a)}catch(e){}})}function Bb(a){var b=a.keyCode;ka[b]=0;delete ka[b];jb(ta,b,a)}function Cb(a){var b=a.which;l(Ia,function(c){if(!c.ec||c.ec==b)try{c.S(a)}catch(d){}})}function Db(a){n(ka,function(b,c){b&&l(ta,function(b){if(!b.A||b.A==c)try{b.S(a)}catch(e){}})})}function kb(a){this.h=a;this.i=a.i;lb(a)||a.ob(function(){lb(a)})}function mb(a,b){var c=[];y(b)?n(b,function(a,b){c.push(encodeURIComponent(b)+"="+encodeURIComponent(a))}):
t(b)&&(c=[b]);c.length&&(a+=(-1!=a.indexOf("?")?"&":"?")+c.join("&"));return a}function O(a){if(!a.wa){var b=a.i.documentElement;if(A(b,"svg"))a.wa=2;else if(A(b,"html")&&(a.wa=1,$&&(b=a.i.getElementById("webmivmlroot"))))a.ia=b,a.wa=3}return a.wa}function lb(a){var b=O(a);if(!b)return 0;if(2==b){var c=a.i.documentElement,b=c.getAttribute("viewBox");a.Sc();if(b)if(b=b.split(" "),4==b.length)for(var d=0;4>d;++d)b[d]=p(b[d]);else b=0;b||(b=[0,0,p(c.getAttribute("width")),p(c.getAttribute("height"))]);
a.Sb(b);c.setAttribute("viewBox",b.join(" "));L["frame.enableautofit"]&&a.pb(function(a,b){c.setAttribute("width",a);c.setAttribute("height",b)});G(a.i,"selectstart",function(a){a.preventDefault&&a.preventDefault()})}else if(3==b){var e=a.i,f=a.ia,b=f.coordorigin,d=f.coordsize,f=a.Q=parseFloat(a.w.getAttribute(f,"http://webmi.atvise.com/2007/svgext","coordfactor"));a.Sb([b.x/f,b.y/f,d.x/f,d.y/f]);var g=a.cc=[],h=a.dc=[];e.body.style.background||(e.body.style.background="transparent");G(e.body,"selectstart",
function(a){a=a.srcElement;return A(a,"input")||A(a,"textarea")});if(L["frame.enableautofit"]){var i=a.q,b=e.getElementById("foreignObjects"),j=a.ya(a.i);b&&b.childNodes&&l(b.childNodes,function(a){if(A(a,"div")){if(j!==s){var b=[];l(a.childNodes,function(a){b.push(a)});Ja(j,a,b)}i.push({element:a,top:p(a.style.top),left:p(a.style.left),width:p(a.style.width),height:p(a.style.height)})}});l("line oval polyline rect roundrect shape".split(" "),function(a){l(e.getElementsByTagName(a),function(a){h.push([a,
a.strokeweight])})});l(e.getElementsByTagName("textpath"),function(a){g.push([a,a.style.fontSize])})}}return 1}function nb(a){this.k=a}function ob(){this.Ha=[]}function pb(a,b){var c=this,d=c.k=b?++Eb:0;c.Ib=[];c.Ba=[];c.Jb=[];c.Mb=[];c.H={};c.M={};E[d]=c;c.t=a;c.i=a.document;c.ua=[];c.Ub=[];c.Nb=[];c.q=[];c.xa=1;c.gd=[];c.da=[];c.qb=new hb(d);c.data=new ib(d);c.w=new qb(c);c.frame=new kb(c);c.keys=new nb(d);c.hb=new ob;b&&(c.Ob(),a.setInterval(function(){c.Ob()},1E3));G(a,"load",function(){c.oc()});
G(a,"unload",function(){c.rb()});G(a,"resize",function(){c.Oa()});G(a,"blur",Db);G(a,"focus",function(){c.nc()});G(c.i,"keydown",Ab);G(c.i,"keyup",Bb);G(c.i,"keypress",Cb)}function Ja(a,b,c){try{a.Oc(b,c)}catch(d){I("foreignObject register function",d)}}function rb(){la=++la%12;n(E,function(a){n(a.H,function(a){if(la in a.value)a.yc[a.functionName](a.tc,a.value[la])})});window.setTimeout(rb,250)}function Ka(a,b){var c=this.h=new pb(a,b),d=c.Pa("");this.alarm=c.qb;this.data=c.data;this.display=c.frame;
this.dom=c.w;this.frame=c.frame;this.sound=c.hb;this.keys=c.keys;this.callExtension=Xa(this,c.t,c.i);var e=c.xb();this.gfx=3==O(c)?new W(c,e,d,""):new Y(c,e,d,"");this.trigger=new La(c,"");this.widget=new Ma(0,d);var f=this.query={},c=a.location.search;l(c.substr("?"==c.charAt(0)?1:0).split("&"),function(a){try{var b=a.split("=");if(2==b.length){var c=decodeURIComponent(b[0]),d=decodeURIComponent(b[1]);2<c.length&&"[]"==c.substr(c.length-2,2)?(c=c.substr(0,c.length-2),c in f||(f[c]=[]),f[c].push(d)):
f[c]=d}}catch(e){}});this.addEvent=Wa(d);this.removeEvent=H()}function qb(a){this.i=a.i;this.n=a.Pa("")}function sb(a,b,c,d,e){this.h=a;this.n=c;this.qa=d;this.Ra=b;this.kc=e;this.uc=0;this.vc={};this.Va={};this.Ta={};this.Ua={};this.Wa={};this.Xa={};this.Ya={};this.Za={}}function ma(a,b){t(b)&&(b=a.n(b));return b}function na(a,b,c,d){var e=b+"Direct";a.prototype["get"+e]=c;a.prototype["get"+b]=function(a){if(a=ma(this,a))return this["get"+e](a)};a.prototype["set"+e]=d;a.prototype["set"+b]=function(a,
b){if(a=ma(this,a)){z(a.yb)||this.h.Qc(a.yb);var c="set"+e;if(y(b)&&b!==s&&!v(b)){a.yb=this.h.hc(a,b,this,c);for(var d=s,j=0;12>j;++j)j in b&&(d=b[j]);for(j=la;0<=j;--j)if(j in b){d=b[j];break}b=d}return this[c](a,b)}}}function Y(a,b,c,d){sb.call(this,a,b,c,d,Fb)}function Fb(a,b,c,d,e,f,g,h,i,j,k,u,m){t(m[b])||(m[b]=a.getAttribute("transform"),m[b]||(m[b]=""));isNaN(d)&&(d=0);isNaN(e)&&(e=0);a.setAttribute("transform","translate("+d+","+e+") rotate("+f+") scale("+i+","+j+") skewX("+k+") skewY("+u+
") translate("+(g-d)+","+(h-e)+") "+m[b])}function ua(a,b){a.style.display=b===s?"":b?"block":"none"}function P(a,b){var c=s;n(a.q,function(a){a.element==b&&(c=a)});return c}function va(a){return[function(b){var c=P(this.h,b);return!c?b.getAttribute(a):c[a]},function(b,c){var d=this.h,e=P(d,b);if(!e)return b.setAttribute(a,c);e[a]=c;d.L()}]}function tb(a,b){if(b===s||!("hasAttribute"in b))return a.createSVGMatrix();var c=tb(a,b.parentNode),d=a.createSVGMatrix();b.hasAttribute("transform")&&(d=ub(d,
b));b.hasAttribute("x")&&(d.e+=p(b.getAttribute("x")));b.hasAttribute("y")&&(d.f+=p(b.getAttribute("y")));return c.multiply(d)}function ub(a,b){for(var c=b.transform.baseVal,d=0;d<c.numberOfItems;++d)a=a.multiply(c.getItem(d).matrix);return a}function W(a,b,c,d){sb.call(this,a,b,c,d,Gb)}function M(a,b){y(a)?(this.x=ga(a.x)?a.x:0,this.y=ga(a.y)?a.y:0):(this.x=ga(a)?a:0,this.y=ga(b)?b:0)}function Gb(a,b,c,d,e,f,g,h,i,j,k,u,m){g*=c;h*=c;k=Z(a.parentNode,c);isNaN(d)&&(d=k.e*c);for(isNaN(e)&&(e=k.f*c);-360>
f;)f+=360;for(;360<f;)f-=360;if(!m[b]){for(var c=s,w=0;w<a.childNodes.length;++w)if(A(a.childNodes[w],"skew")){c=a.childNodes[w];break}if(c)return console.error("Element '"+b+"' has a skew Element, which is not implemented yet");k=s;if(A(a,"line"))k={from:new M(a.from),to:new M(a.to)},k.center=new M((k.from.x+k.to.x)/2,(k.from.y+k.to.y)/2);else if(A(a,"polyline")){k={points:[],rotation:p(a.style.rotation)};isNaN(k.rotation)&&(k.rotation=0);for(var q,J,D,l,u=a.points.value.replace(" ",",").split(","),
w=0;w<u.length;w+=2)c=new M(p(u[w]),p(u[w+1])),k.points.push(c),0==w?(q=J=c.x,D=l=c.y):(c.x<J&&(J=c.x),c.y<l&&(l=c.y),c.x>q&&(q=c.x),c.y>D&&(D=c.y));k.center=new M((J+q)/2,(l+D)/2)}else k={left:p(a.style.left),top:p(a.style.top),width:p(a.style.width),height:p(a.style.height),rotation:p(a.style.rotation)},isNaN(k.rotation)&&(k.rotation=0),k.center=new M(k.left+k.width/2,k.top+k.height/2);m[b]=k}q={};for(w in m[b])q[w]=m[b][w];w=new M(d,e);if(A(a,"line"))d=new M(q.from),e=new M(q.to),d.rotate(w,f),
e.rotate(w,f),a.from=d.x+g+","+(d.y+h),a.to=e.x+g+","+(e.y+h);else if(w.rotate(new M(d+(q.center.x-d)*i,e+(q.center.y-e)*j),f),g=g+d-w.x,h=h+e-w.y,A(a,"polyline")){b="";for(w=0;w<q.points.length;++w)0<w&&(b+=","),c=q.points[w],b+=(c.x+(d-c.x)*(1-i)+g).toFixed(5)+","+(c.y+(e-c.y)*(1-j)+h).toFixed(5);a.points.value=b;a.style.rotation=q.rotation+f}else q.left+=(d-q.left)*(1-i),q.top+=(e-q.top)*(1-j),q.width*=i,q.height*=j,a.style.left=q.left+g,a.style.top=q.top+h,a.style.rotation=q.rotation+f,a.style.width=
0<q.width?q.width:0,a.style.height=0<q.height?q.height:0;return m}function Z(a,b){if(A(a,"group")){var c=Z(a.parentNode,b),d=new ba,e=a.getAttribute("atv:origtransform");e&&(e=e.slice(7,e.length-1).split(","),d=$a(d,e));d.e+=a.getAttribute("atv:origx")?p(a.getAttribute("atv:origx"))/b:0;d.f+=a.getAttribute("atv:origy")?p(a.getAttribute("atv:origy"))/b:0;return c.multiply(d)}return new ba}function Na(a){function b(a,b){g?(a<c&&(c=a),a>d&&(d=a),b<e&&(e=b),b>f&&(f=b)):(c=d=a,e=f=b,g=r)}for(var c,d,e,
f,g=F,h=0;h<a.childNodes.length;++h){var i=a.childNodes[h],j=i.style;if(A(i,"polyline")){var k=i.points;l(k,function(a,c){var d=k.item(c);b(d.x,d.y)})}var i=parseInt(j.width),u=parseInt(j.height);if(0<i&&0<u){var m=parseInt(j.left),j=parseInt(j.top);b(m,j);b(m+i,j+u)}}g&&(a.style.left=c,a.style.top=e,a.style.height=f-e,a.style.width=d-c,a.coordsize=d-c+","+(f-e),a.coordorigin=c+","+e);a=a.parentNode;A(a,"group")&&("webmivmlroot"!=a.id&&""!=a.id)&&Na(a)}function X(a,b,c,d){a=a.createElement("v:"+b);
R(a,c,d);return a}function R(a,b,c){for(var d in b)a[d]=b[d];for(d in c)a.style[d]=c[d]}function La(a,b){this.h=a;this.aa=b}function vb(a){this.n=a}function wb(a,b){this.n=b}function Ma(a,b){this.n=b;this.checkbox=new vb(b);this.combobox=new wb(0,b)}function Hb(a,b,c,d,e,f,g){var h=b.h,i=h.Pa(e);this.Xb=aa(a.document,{getElementById:i});b=this.Yb=aa(b,{addEvent:Wa(i),gfx:3==O(h)?new W(h,d,i,c):new Y(h,d,i,c),parentWindow:g,query:f,trigger:new La(h,e),widget:new Ma(0,i)});this.jb=aa(a,{document:this.Xb,
webMI:this.Yb});b.callExtension=Xa(b,h.t,h.i)}var $=/MSIE (\d+)\./.test(navigator.userAgent)?1*RegExp.$1:0,zb=$,p=parseFloat,x="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+/",U=[],la=0,Eb=0,Ib=0,E={},Jb=0,Kb=0,Oa={},Q=new Ea(r),V=new Ea(F),ea={},wa={},ja="",T={},eb=F,oa={},Pa=s,Qa="",Ra="",Aa={},Ha=[],Ga=[],ta=[],Ia=[],ka=[],xb=s,Sa=s,Ta=[],L={"data.enabledeletesession":r,"data.enablelongpoll":r,"data.publishinterval":0,"frame.enableautofit":r};B(ba,{inverse:function(){var a=[this.a,
this.b,this.c,this.d,this.e,this.f],b=a[0]*a[3]-a[2]*a[1];if(0!=b)for(var c=[[a[3],-a[1],0],[-a[2],a[0],0],[a[2]*a[5]-a[3]*a[4],a[0]*-a[5]+a[1]*a[4],a[0]*a[3]-a[1]*a[2]]],d=0;3>d;d++)for(var e=0;2>e;e++)a[2*d+e]=c[d][e]/b;return $a(new ba,a)},multiply:function(a){var b=new ba;b.a=this.a*a.a+this.c*a.b;b.b=this.b*a.a+this.d*a.b;b.c=this.a*a.c+this.c*a.d;b.d=this.b*a.c+this.d*a.d;b.e=this.a*a.e+this.c*a.f+this.e;b.f=this.b*a.e+this.d*a.f+this.f;return b}});Ca.prototype.matrixTransform=function(a){var b=
new Ca;b.x=this.x*a.a+this.y*a.c+a.e;b.y=this.x*a.b+this.y*a.d+a.f;return b};ab(window);G(window,"unload",function(){L["data.enabledeletesession"]&&n(T,function(a){l(a,function(a){z(a.K)||a.m("deletesession",0,s,H())})})});B(db,{ca:function(){return this.pa.Na},m:function(a,b,c,d){function e(){f.pa.m(a,b,f.zc,c,d)}var f=this;f.Ea&&b&2?f.Ea.push(e):e()},Tb:function(a){this.ib=a;l(this.Ea,ia("queued request"));delete this.Ea},ea:function(a,b,c,d,e){if(this.ca()&&c in a){var a=a[c],f=a.Aa,g=!e||z(f);
g||n(d,function(a,b){f[b]!==a&&(g=r)});g&&b.eb(c,a.Aa=d)}},ub:function(a,b,c){var d=this;d.ib||d.Tb(1);d.Da=r;d.m(a,1,b,function(a){d.Da=F;l(a.result,function(a,b){d.ea(d.U,d.ha,c[b],a,r)});d.gb()})},$:function(a){var b=this;if(b.pa.p!==s&&!(z(b.bb)||b.ib==a))switch(b.pa.p||(b.I=9),b.I){case 9:alert("INVALID LICENSE");case 5:case 6:break;case 2:var c=[],d=[];n(b.U,function(a,b){c.push(b);d.push("address[]="+encodeURIComponent(b))});return b.ub("read",d,c);case 4:return b.ub("readprocessimage",s,b.Pb);
case 7:if(!b.ib)return b.Tb(a),setTimeout(function(){b.$()},50);b.Da=r;b.m("publish",1,L["data.enablelongpoll"]?s:"longpoll=false",function(a){b.Da=F;if(a.error||a.httpstatus===0)cb();else{l(a.result,function(a){var c=a.subscriptionid;delete a.subscriptionid;l(c,function(c){if(c==b.cb){var c=a.address,d=a.type;delete a.type;d==1?b.ea(b.U,b.ha,c,a,F):d==2?b.ea(b.la,b.na,c,a,F):o("Unknown type '"+d+"' of publish item.")}else if(b.ca())if(c==""){n(a,function(a,b){oa[b]=a});n(E,function(a){a.data&&l(a.data.Hb,
function(a){try{a(oa)}catch(b){}})})}else if(c in b.V){c=b.V[c];if(c in wa)try{wa[c](a)}catch(e){I("publish callback of filter '"+c+"'",e)}}else o("Unknown subscription "+c)})});console.log("Published "+a.result.length+"item(s)");b.gb()}})}},gb:function(){var a=this;if(!a.Da&&!a.fb){var b=L["data.publishinterval"];b?(a.fb=r,setTimeout(function(){a.fb=F;a.gb()},b)):a.fb=F;a.$()}},ac:function(a,b,c){if(b in a){var d=a[b];if(4==d.state||3==d.state)return d.state=3,this.ea(a,c,b,d.Aa,F)}a[b]={state:1};
this.Ka=r},W:function(a,b){var c=a[b];1==c.state||9==c.state?delete a[b]:(c.state=4,this.Ka=r)},$b:function(a){return this.ac(this.U,a,this.ha)},Xc:function(a){return this.W(this.U,a)},Zb:function(a){return this.ac(this.la,a,this.na)},Wc:function(a){return this.W(this.la,a)},Fc:function(a){function b(b,e,f,g){var h=["subscriptionid="+encodeURIComponent(c.cb)],i=[],j=[];n(b,function(a,b){1==a.state?i.push(b):4==a.state&&j.push(b)});return j.length?(l(j,function(a){h.push("address[]="+encodeURIComponent(a));
b[a].state=5}),c.m(g,1,h,function(c){c=c.result;c.length!=j.length&&o("Length of "+g+".result doesn't match.");l(c,function(a,c){var e=j[c],q=b[e];a.error?(console.warn("Can't "+g+": "+e),q.state=1==q.state?3:4):5==q.state&&delete b[e]});a()}),r):i.length?(l(i,function(a){h.push("address[]="+encodeURIComponent(a));b[a].state=2}),c.m(f,1,h,function(g){if(g.error)return l(i,function(a){b[a].state=9;c.ea(b,e,a,g,F)});var h=g.result;h.length!=i.length&&o("Length of "+f+".result doesn't match.");l(h,function(a,
g){var q=i[g],h=b[q];a.error?(console.warn("Can't "+f+": "+q),4==h.state?delete b[q]:(h.state=9,c.ea(b,e,q,a,F))):2==h.state&&(h.state=3)});a()}),r):F}var c=this;if(c.Ka){if(b(c.U,c.ha,"subscribedata","unsubscribedata")||b(c.la,c.na,"subscribealarm","unsubscribealarm"))return r;c.Ka=F}return F},fd:function(){n(self.U,function(a,b){self.ha.eb(b,a.Aa)});n(self.la,function(a,b){self.na.eb(b,a.Aa)})}});B(fb,{qc:function(a,b,c){ca(a).push(this.Rc[a]=new db(this,b,c))},setActive:function(a){this.Na=a},
ca:function(){return this.Na},vb:function(a){var b=this.bb,c=b.encryptionexponent,b=b.encryptionmodulus;if(t(c)&&t(b)&&""!=c&&""!=b){var d=function(a,b,c){a!=s&&("number"==typeof a?this.ad(a,b,c):b==s&&"string"!=typeof a?this.wb(a,256):this.wb(a,b))},e=function(){return new d(s)},f=function(a,b,c,d,e,g){for(;0<=--g;){var f=b*this[a++]+c[d]+e,e=Math.floor(f/67108864);c[d++]=f&67108863}return e},g=function(a,b,c,d,e,g){for(var f=b&32767,b=b>>15;0<=--g;){var h=this[a]&32767,i=this[a++]>>15,j=b*h+i*f,
h=f*h+((j&32767)<<15)+c[d]+(e&1073741823),e=(h>>>30)+(j>>>15)+b*i+(e>>>30);c[d++]=h&1073741823}return e},h=function(a,b,c,d,e,g){for(var f=b&16383,b=b>>14;0<=--g;){var h=this[a]&16383,i=this[a++]>>14,j=b*h+i*f,h=f*h+((j&16383)<<14)+c[d]+e,e=(h>>28)+(j>>14)+b*i;c[d++]=h&268435455}return e},i=function(a){var b=e();b.xc(a);return b},j=function(a){var b=1,c;if(0!=(c=a>>>16))a=c,b+=16;if(0!=(c=a>>8))a=c,b+=8;if(0!=(c=a>>4))a=c,b+=4;if(0!=(c=a>>2))a=c,b+=2;0!=a>>1&&(b+=1);return b},k=function(a){this.o=
a},l=function(a){this.o=a;this.Cb=a.Ac();this.Db=this.Cb&32767;this.Kc=this.Cb>>15;this.Vc=(1<<a.l-15)-1;this.Lc=2*a.g};"Microsoft Internet Explorer"==navigator.appName?(d.prototype.D=g,f=30):"Netscape"!=navigator.appName?(d.prototype.D=f,f=26):(d.prototype.D=h,f=28);d.prototype.l=f;d.prototype.B=(1<<f)-1;d.prototype.C=1<<f;d.prototype.gc=Math.pow(2,52);d.prototype.lb=52-f;d.prototype.mb=2*f-52;for(var m=[],f=48,g=0;9>=g;++g)m[f++]=g;f=97;for(g=10;36>g;++g)m[f++]=g;f=65;for(g=10;36>g;++g)m[f++]=g;
k.prototype.tb=function(a){return a.j<0||a.ga(this.o)>=0?a.Gc(this.o):a};k.prototype.Rb=function(a){return a};k.prototype.reduce=function(a){a.Sa(this.o,a)};k.prototype.Eb=function(a,b,c){a.Fb(b,c);this.reduce(c)};k.prototype.Vb=function(a,b){a.Wb(b);this.reduce(b)};l.prototype.tb=function(a){var b=e();a.abs().ra(this.o.g,b);b.Sa(this.o,b);a.j<0&&b.ga(d.ZERO)>0&&this.o.r(b,b);return b};l.prototype.Rb=function(a){var b=e();a.copyTo(b);this.reduce(b);return b};l.prototype.reduce=function(a){for(;a.g<=
this.Lc;)a[a.g++]=0;for(var b=0;b<this.o.g;++b){var c=a[b]&32767,d=c*this.Db+((c*this.Kc+(a[b]>>15)*this.Db&this.Vc)<<15)&a.B,c=b+this.o.g;for(a[c]=a[c]+this.o.D(0,d,a,b,0,this.o.g);a[c]>=a.C;){a[c]=a[c]-a.C;a[++c]++}}a.F();a.sc(this.o.g,a);a.ga(this.o)>=0&&a.r(this.o,a)};l.prototype.Eb=function(a,b,c){a.Fb(b,c);this.reduce(c)};l.prototype.Vb=function(a,b){a.Wb(b);this.reduce(b)};d.prototype.copyTo=function(a){for(var b=this.g-1;b>=0;--b)a[b]=this[b];a.g=this.g;a.j=this.j};d.prototype.xc=function(a){this.g=
1;this.j=a<0?-1:0;a>0?this[0]=a:a<-1?this[0]=a+DV:this.g=0};d.prototype.wb=function(a,b){var c;if(b==16)c=4;else if(b==8)c=3;else if(b==256)c=8;else if(b==2)c=1;else if(b==32)c=5;else if(b==4)c=2;else{this.bd(a,b);return}this.j=this.g=0;for(var e=a.length,g=F,f=0;--e>=0;){var h;if(c==8)h=a[e]&255;else{h=m[a.charCodeAt(e)];h=h==s?-1:h}if(h<0)a.charAt(e)=="-"&&(g=r);else{g=F;if(f==0)this[this.g++]=h;else if(f+c>this.l){this[this.g-1]=this[this.g-1]|(h&(1<<this.l-f)-1)<<f;this[this.g++]=h>>this.l-f}else this[this.g-
1]=this[this.g-1]|h<<f;f=f+c;f>=this.l&&(f=f-this.l)}}if(c==8&&(a[0]&128)!=0){this.j=-1;f>0&&(this[this.g-1]=this[this.g-1]|(1<<this.l-f)-1<<f)}this.F();g&&d.ZERO.r(this,this)};d.prototype.F=function(){for(var a=this.j&this.B;this.g>0&&this[this.g-1]==a;)--this.g};d.prototype.ra=function(a,b){var c;for(c=this.g-1;c>=0;--c)b[c+a]=this[c];for(c=a-1;c>=0;--c)b[c]=0;b.g=this.g+a;b.j=this.j};d.prototype.sc=function(a,b){for(var c=a;c<this.g;++c)b[c-a]=this[c];b.g=Math.max(this.g-a,0);b.j=this.j};d.prototype.zb=
function(a,b){var c=a%this.l,d=this.l-c,e=(1<<d)-1,g=Math.floor(a/this.l),f=this.j<<c&this.B,h;for(h=this.g-1;h>=0;--h){b[h+g+1]=this[h]>>d|f;f=(this[h]&e)<<c}for(h=g-1;h>=0;--h)b[h]=0;b[g]=f;b.g=this.g+g+1;b.j=this.j;b.F()};d.prototype.Nc=function(a,b){b.j=this.j;var c=Math.floor(a/this.l);if(c>=this.g)b.g=0;else{var d=a%this.l,e=this.l-d,g=(1<<d)-1;b[0]=this[c]>>d;for(var f=c+1;f<this.g;++f){b[f-c-1]=b[f-c-1]|(this[f]&g)<<e;b[f-c]=this[f]>>d}d>0&&(b[this.g-c-1]=b[this.g-c-1]|(this.j&g)<<e);b.g=
this.g-c;b.F()}};d.prototype.r=function(a,b){for(var c=0,d=0,e=Math.min(a.g,this.g);c<e;){d=d+(this[c]-a[c]);b[c++]=d&this.B;d=d>>this.l}if(a.g<this.g){for(d=d-a.j;c<this.g;){d=d+this[c];b[c++]=d&this.B;d=d>>this.l}d=d+this.j}else{for(d=d+this.j;c<a.g;){d=d-a[c];b[c++]=d&this.B;d=d>>this.l}d=d-a.j}b.j=d<0?-1:0;d<-1?b[c++]=this.C+d:d>0&&(b[c++]=d);b.g=c;b.F()};d.prototype.Fb=function(a,b){var c=this.abs(),e=a.abs(),g=c.g;for(b.g=g+e.g;--g>=0;)b[g]=0;for(g=0;g<e.g;++g)b[g+c.g]=c.D(0,e[g],b,g,0,c.g);
b.j=0;b.F();this.j!=a.j&&d.ZERO.r(b,b)};d.prototype.Wb=function(a){for(var b=this.abs(),c=a.g=2*b.g;--c>=0;)a[c]=0;for(c=0;c<b.g-1;++c){var d=b.D(c,b[c],a,2*c,0,1);if((a[c+b.g]=a[c+b.g]+b.D(c+1,2*b[c],a,2*c+1,d,b.g-c-1))>=b.C){a[c+b.g]=a[c+b.g]-b.C;a[c+b.g+1]=1}}a.g>0&&(a[a.g-1]=a[a.g-1]+b.D(c,b[c],a,2*c,0,1));a.j=0;a.F()};d.prototype.Sa=function(a,b){var c=a.abs();if(!(c.g<=0)){var g=this.abs();if(g.g<c.g)b!=s&&this.copyTo(b);else{b==s&&(b=e());var f=e(),h=this.j,i=this.l-j(c[c.g-1]);if(i>0){c.zb(i,
f);g.zb(i,b)}else{c.copyTo(f);g.copyTo(b)}c=f.g;g=f[c-1];if(g!=0){var k=g*(1<<this.lb)+(c>1?f[c-2]>>this.mb:0),m=this.gc/k,k=(1<<this.lb)/k,l=1<<this.mb,n=b.g,u=n-c,p=e();f.ra(u,p);if(b.ga(p)>=0){b[b.g++]=1;b.r(p,b)}d.ONE.ra(c,p);for(p.r(f,f);f.g<c;)f[f.g++]=0;for(;--u>=0;){var t=b[--n]==g?this.B:Math.floor(b[n]*m+(b[n-1]+l)*k);if((b[n]=b[n]+f.D(0,t,b,u,0,c))<t){f.ra(u,p);for(b.r(p,b);b[n]<--t;)b.r(p,b)}}b.g=c;b.F();i>0&&b.Nc(i,b);h<0&&d.ZERO.r(b,b)}}}};d.prototype.Ac=function(){if(this.g<1)return 0;
var a=this[0];if((a&1)==0)return 0;var b=a&3,b=b*(2-(a&15)*b)&15,b=b*(2-(a&255)*b)&255,b=b*(2-((a&65535)*b&65535))&65535,b=b*(2-a*b%this.C)%this.C;return b>0?this.C-b:-b};d.prototype.Cc=function(){return(this.g>0?this[0]&1:this.j)==0};d.prototype.exp=function(a,b){if(a>4294967295||a<1)return d.ONE;var c=e(),g=e(),f=b.tb(this),h=j(a)-1;for(f.copyTo(c);--h>=0;){b.Vb(c,g);if((a&1<<h)>0)b.Eb(g,f,c);else var i=c,c=g,g=i}return b.Rb(c)};d.prototype.toString=function(a){if(this.j<0)return"-"+this.Gb().toString(a);
if(a==16)a=4;else if(a==8)a=3;else if(a==2)a=1;else if(a==32)a=5;else if(a==4)a=2;else return this.hd(a);var b=(1<<a)-1,c,d=F,e="",g=this.g,f=this.l-g*this.l%a;if(g-- >0){if(f<this.l&&(c=this[g]>>f)>0){d=r;e=x.charAt(c)}for(;g>=0;){if(f<a){c=(this[g]&(1<<f)-1)<<a-f;c=c|this[--g]>>(f=f+(this.l-a))}else{c=this[g]>>(f=f-a)&b;if(f<=0){f=f+this.l;--g}}c>0&&(d=r);d&&(e=e+x.charAt(c))}}return d?e:"0"};d.prototype.Gb=function(){var a=e();d.ZERO.r(this,a);return a};d.prototype.abs=function(){return this.j<
0?this.Gb():this};d.prototype.ga=function(a){var b=this.j-a.j;if(b!=0)return b;var c=this.g,b=c-a.g;if(b!=0)return b;for(;--c>=0;)if((b=this[c]-a[c])!=0)return b;return 0};d.prototype.mc=function(){return this.g<=0?0:this.l*(this.g-1)+j(this[this.g-1]^this.j&this.B)};d.prototype.Gc=function(a){var b=e();this.abs().Sa(a,b);this.j<0&&b.ga(d.ZERO)>0&&a.r(b,b);return b};d.prototype.Hc=function(a,b){var c;c=a<256||b.Cc()?new k(b):new l(b);return this.exp(a,c)};d.ZERO=i(0);d.ONE=i(1);b=new d(b,16);c=parseInt(c,
16);f=b.mc()+7>>3;f<a.length+11&&o("Message is too long for encryption");i=[];for(g=a.length;0<g;)i[--f]=a.charCodeAt(--g);for(i[--f]=0;2<f;)i[--f]=1+Math.round(254*Math.random());i[--f]=2;i[--f]=0;a=(new d(i)).Hc(c,b);a==s?a=s:(a=a.toString(16),a=a.length%2?"0"+a:a)}else a="";return a},m:function(a,b,c,d,e,f){function g(){try{var g=i.status;if(200==g){var j=i.responseText;if(""!=j){try{var m=JSON.parse(j)}catch(l){I("parsing JSON",l);cb();return}return e(m)}g=0}if(12029<=g&&12031>=g||12152==g)g=
0;f=f?f:0;return 4>f&&401!=g?(console.warn("Can't receive response for '"+a+"' (retry #"+f+")"),h.m(a,b,c,d,e,f+1)):e({error:-1E3-g,errorstring:"HTTP "+i.statusText,httpstatus:g})}catch(q){I("handling response",q)}finally{Ta.push(i)}}var h=this,i=Ta.length?Ta.pop():new XMLHttpRequest;i.open("POST",h.Yc+a,b&1?r:F);z(h.K)||(++h.Z,i.setRequestHeader("X-WebMI",'sessionid="'+h.K+'", cnonce="'+h.Z+'", digest="'+Ba(h.K+":"+h.s+":"+h.Z)+'"'+c));var j="onloadend"in i;j&&(i.onloadend=g);i.onreadystatechange=
function(){if(i.readyState==4&&!j)g();else if(i.readyState==2&&!S(a,["login","publish","queryfilter"])){Pa=Date.parse(i.getResponseHeader("Date"))-new Date;n(E,function(a){a.data&&l(a.data.Kb,function(a){try{a(Pa)}catch(b){}})})}};d!==s&&(v(d)&&(d=d.join("&")),i.setRequestHeader("Content-Type","application/x-www-form-urlencoded"));i.send(d)}});B(gb,{Bc:function(){return ha(this.u)&&ha(this.T)},ta:function(a){var b=this;n(b.u,function(c,d){n(c.O,function(c,f){l(c,function(c,e){a(b,d,f,c,e)})})})},
Ab:function(a){this.ta(function(b,c,d,e,f){a.fa(e.va,c,e.N,d,e.ka);b.W(c,d,f)})},fa:function(a,b,c,d,e){var f;f=this.u;b in f?f=f[b]:(f=f[b]={state:0,O:{}},l(this.Qb,this.ja?function(a){a.Zb(b)}:function(a){a.$b(b)}));d in f.O||(f.O[d]=[]);e||(e=++Jb);f.O[d].push({ka:e,va:a,N:c});a=f.Ec;z(a)||(a.address=d,c(a),delete a.address);return e},La:function(a){var b=F;this.ta(function(c,d,e,f,g){f.ka==a&&(c.W(d,e,g),b=r)});return b},Ma:function(a){var b=[];for(this.ta(function(c,e,f,g,h){g.va==a&&b.push({ma:e,
oa:f,za:h})});b.length;){var c=b.pop();this.W(c.ma,c.oa,c.za)}},W:function(a,b,c){var d=this.u[a].O;d[b].splice(c,1);d[b].length||(delete d[b],ha(d)&&(delete this.u[a],l(this.Qb,this.ja?function(b){b.Wc(a)}:function(b){b.Xc(a)})))},kb:function(a){var b=[];n(this.u,function(c,d){n(c.O,function(c){l(c,function(c){c.va==a&&!S(d,b)&&b.push(d)})})});return b},Ca:function(a){var b=[];a in this.T||(this.T[a]=[]);for(this.ta(function(c,e,f,g,h){g.va==a&&b.push({ma:e,oa:f,za:h,N:g.N,ka:g.ka})});b.length;){var c=
b.pop();this.W(c.ma,c.oa,c.za);delete c.za;this.T[a].push(c)}},Fa:function(a){var b=this;a in b.T&&(l(b.T[a],function(c){b.fa(a,c.ma,c.N,c.oa,c.ka)}),delete b.T[a])},eb:function(a,b){if(a in this.u){var c=this.u[a];n(c.O,function(a,c){b.address=c;l(a,function(a){try{a.N(b)}catch(d){I("publish callback of address '"+c+"'",d)}})});c.Ec=b}},Ja:function(a){n(this.u,this.ja?function(b,c){a.Zb(c)}:function(b,c){a.$b(c)});return this}});B(Ea,{sb:function(){var a=this.J;n(a,function(b,c){b.Bc()&&""!=c&&delete a[c]})},
sa:function(a){var b=this.J;a in b||(b[a]=new gb(this.ja,a));return b[a]},Bb:function(a){var b=this.J,c=this.sa("");a===s?n(b,function(a,e){a!=c&&(a.Ab(c),delete b[e])}):(this.sa(a).Ab(c),delete b[a])},kb:function(a){var b={};n(this.J,function(c,d){b[d]=c.kb(a)});return b},Ia:function(a,b,c){(!t(b)||!C(c))&&N();var d=ra(b);return this.sa(qa(b)).fa(a,d,c,b)},bc:function(a,b){var c=F;n(this.J,function(a){a.La(b)&&(c=r)});this.sb();return c},fa:function(a,b,c){var d=this;if(v(b)){var e=[];l(b,function(b,
g){e[g]=d.Ia(a,b,c)});return e}return y(b)?(e={},n(b,function(b,c){C(b)||N();e[c]=d.Ia(a,c,b)}),e):this.Ia(a,b,c)},La:function(a,b){var c=this;if(v(b)){var d=[];l(b,function(b,f){d[f]=c.bc(a,b)});return d}return this.bc(a,b)},Ma:function(a){n(this.J,function(b){b.Ma(a)});this.sb()},Ca:function(a){n(this.J,function(b){b.Ca(a)})},Fa:function(a){n(this.J,function(b){b.Fa(a)})},Ja:function(a,b){return this.sa(a).Ja(b)}});B(hb,{accept:function(a,b){function c(a,b){var c=qa(a),a="address[]="+encodeURIComponent(ra(a));
c in e?(e[c].push(b),f[c].push(a)):(e[c]=[b],f[c]=[a])}var d=[],e={},f={};t(a)?c(a):v(a)?l(a,c):N();da("acceptalarm",f,function(c){n(c,function(b,c){var g=b.result;t(a)?d=b.error?b:g[0]:l(e[c],function(a,c){d[a]=b.error?b:g[c]})});C(b)&&b(d)})},acceptDisplay:function(){var a=Q.kb(this.k);n(a,function(a){l(a,function(c,d){a[d]="address[]="+encodeURIComponent(c)})});da("acceptalarm",a,H())},subscribe:function(a,b){return Q.fa(this.k,a,b)},unsubscribe:function(a){return Q.La(this.k,a)}});B(ib,{addEventListener:function(a,
b){"clientvariableschange"==a?(this.Hb.push(b),b(oa)):"servertimeoffsetchanged"==a?(b(Pa),this.Kb.push(b)):"statechange"==a&&this.Lb.push(b)},removeEventListener:H(),pause:function(){V.Ca(this.k);Q.Ca(this.k)},resume:function(){V.Fa(this.k);Q.Fa(this.k)},call:function(a,b,c,d){var e=t(c)?c:"",f=C(c)?c:d,c={};c[e]=t(b)?b:Fa(b);da(a,c,function(a){C(f)&&f(a[e])})},login:function(a,b,c){var d={};n(Oa,function(c,f){d[f]=!t(a)||!t(b)?s:["username="+encodeURIComponent(a),"passwordcipher="+encodeURIComponent(c.vb(b)),
"passworddigest="+encodeURIComponent(Ba(c.K+":"+c.s+":"+b))]});da("login",d,C(a)?a:C(c)?c:H())},logout:function(a){var b={};n(Oa,function(a,d){b[d]=s});da("logout",b,C(a)?a:H())},read:function(a,b){function c(a,b){var c=qa(a),a=ra(a);c in e?(e[c].push(b),f[c].push(a)):(e[c]=[b],f[c]=[a])}var d=[],e={},f={};if(C(b)){t(a)?c(a):v(a)?l(a,c):y(a)&&(d={},n(a,c));var g=0;n(f,function(c,f){function j(){var a=ea[f];if(ha(a))delete ea[f];else{ea[f]={};bb(f,a,j)}}function k(c,e){if(t(a))return b(c);d[e]=c;--g||
b(d)}g=g+c.length;var n=e[f],m=f in ea,p={};m?p=ea[f]:ea[f]={};l(c,function(a,b){var c={N:k,key:n[b]};a in p?p[a].push(c):p[a]=[c]});m||bb(f,p,j)})}},write:function(a,b,c){function d(a,b,c){var d=qa(a),a="address[]="+encodeURIComponent(ra(a))+"&value[]="+sa(b);d in g?(g[d].push(c),h[d].push(a)):(g[d]=[c],h[d]=[a])}var e=C(b)?b:c,f=[],g={},h={};if(t(a))d(a,b);else if(v(a))if(v(b))for(c=0;c<a.length&&c<b.length;++c)d(a[c],b[c],c);else y(b)||l(a,function(a,c){d(a,b,c)});else y(a)&&(f={},n(a,function(a,
b){d(b,a,b)}));da("write",h,function(b){n(b,function(b,c){var d=b.result;t(a)?f=d[0]:l(d,function(a,b){f[g[c][b]]=a})});C(e)&&e(f)})},subscribe:function(a,b){return V.fa(this.k,a,b)},unsubscribe:function(a){return V.La(this.k,a)},subscribeBlock:function(a,b,c){function d(a,b,c){l(b,function(b,d){a.Ia(g,b,function(a){i[d+c]=a;h||(h=r,l(i,function(a){h=h&&!z(a)}));h&&f(i)})})}var e=[],f=c;v(a)&&v(b)&&C(c)?e=b:v(a)&&C(b)?f=b:N();var g=this.k,h=F,i=Array(a.length+e.length);d(V,a,0);d(Q,e,a.length)},subscribeFilter:function(a,
b,c){var d=t(b)?b:"",b=C(b)?b:c,e=Fa(a);e.splice(0,0,"");var f=++Kb;this.V.push(f);wa[f]=b;l(ca(d),function(a){a.m("createsubscription",3,s,function(b){b=b.subscriptionid;a.V[b]=f;e[0]="subscriptionid="+encodeURIComponent(b);a.m("subscribefilter",3,e,H())})});return f},unsubscribeFilter:function(a){n(T,function(b){l(b,function(b){n(b.V,function(d,e){d==a&&b.m("deletesubscription",3,"subscriptionid="+encodeURIComponent(e),H())})})});delete wa[a]},queryFilter:function(a,b,c){var d=t(b)?b:"",e=C(b)?
b:c,f=Fa(a);C(e)||N();l(ca(d),function(a){a.ca()&&a.m("queryfilter",3,f,e)})}});B(kb,{createURL:function(a,b){return mb(Ra+encodeURIComponent(a)+Qa,b)},getViewBox:function(){return this.h.P},getInitialViewBox:function(){return this.h.$a},setViewBox:function(a,b,c,d){var e=this.h;e.P=[a,b,c,d];this.isSVG()&&e.i.documentElement.setAttribute("viewBox",e.P.join(" "));e.Oa()},getURLPostfix:function(){return Qa},getURLPrefix:function(){return Ra},isRoot:function(){return!this.h.k},isHTML:function(){return 1==
O(this.h)},isSVG:function(){return 2==O(this.h)},isVML:function(){return 3==O(this.h)},setEnableAutoFit:function(a){L["frame.enableautofit"]=!!a},setForeignObjectHandler:function(a,b,c,d,e,f,g){C(b)&&(b={create:b,destroy:H(),set:c,add:d,remove:e,register:f,applyOffsetsToMatrix:g},console.warn("Using deprecated version of setForeignObjectHandler()"));this.h.Tc(a,b)},setURLPostfix:function(a){Qa=a},setURLPrefix:function(a){Ra=a},setOpenUrlHandler:function(a){fa=a},setOpenWindowHandler:function(a,b){this.h.Nb.push({ba:a,
z:b})},setShowPopupHandler:function(a,b){this.h.Ub.push({ba:a,z:b})},openDisplay:function(a,b,c){return this.openUrl(this.createURL(a),b,c)},openUrl:function(a,b,c){z(c)&&(c=this.h.t);return fa(mb(a,b),c)},openWindow:function(a,b,c,d,e,f,g,h){var i=s,j=this;n(E,function(a){n(a.Nb,function(a){ya(a.ba,j.i)&&(i=a)})});if(i){var k=j.h.da,l;try{l=i.z.apply(s,arguments)}catch(m){l=i.z.call(s,a,b,c,d,e,f,g,h)}if(!ha(l)){var p=l.close;l.close=function(){pa(k,function(a){return a==l});p.apply(l,arguments)};
k.push(l)}return l}},closeWindow:function(a){if(a&&"close"in a)return a.close();var b=r,c=this.i;n(E,function(a){a&&n(a.da,function(a){za(a,c)&&(a.close(),b=F)})});b&&this.h.t.close()},showPopup:function(a,b,c){var d=s,e=this.i;n(E,function(a){n(a.Ub,function(a){ya(a.ba,e)&&(d=a)})});if(d)return d.z(a,b,c)}});B(nb,{addCombinationListener:function(a,b,c){Ha.push({k:this.k,Jc:a,A:b,S:c})},addDownListener:function(a,b){Ga.push({k:this.k,A:b,S:a})},addUpListener:function(a,b){ta.push({k:this.k,A:b,S:a})},
addPressListener:function(a,b){Ia.push({k:this.k,ec:b,S:a})},isDown:function(a){return a in ka}});B(ob,{setHandler:function(a,b){xb=a;Sa=b},play:function(){var a=xb.apply(s,arguments);a&&this.Ha.push(a);return a},stop:function(){var a=Sa.apply(s,arguments);pa(this.Ha,function(b){return b==a});return a}});var xa=[4,2,-3,-11,-8,5,12,-3,8,1,19,-4,-5,8,-16,-4];l(xa,function(a,b){x+=x.charAt((1<<(9-b?5:6))+(b%2?-1:1)*a)});var Lb=x.substr(4*xa[10]-2,xa[0]+xa[1]).toUpperCase(),yb;yb=(Oa[""]=new fb("/webMI/?"))===
s;B(pb,{author:Lb+(yb?x:""),ic:function(a){this.Ib.push(a)},ob:function(a){this.Ba?this.Ba.push(a):ia("load")(a)},pb:function(a){this.Jb.push(a)},jc:function(a){this.Mb.push(a)},Ob:function(){this.Dc=new Date;this.Pc=5},nc:function(){l(this.Ib,ia("focus"))},oc:function(){l(this.Ba,ia("load"));this.Ba=s;this.Oa()},rb:function(){l(this.Mb,ia("unload"));var a=this,b=a.k;l([Ha,Ga,ta,Ia],function(a){pa(a,function(a){return a.k==b})});a.keys=s;var c=a.frame;c.h=s;c.i=s;a.frame=s;c=a.w;c.i=c.n=s;a.w=s;var d=
a.data;l(d.V,function(a){d.unsubscribeFilter(a)});V.Ma(d.k);a.data=s;Q.Ma(b);a.qb=s;c=a.hb;l(c.Ha,function(a){Sa(a)});c.Ha=s;a.hb=s;a.ia=s;for(l(a.q,function(a){try{a.z.remove(a.element),a.z.rc(a.element)}catch(b){I("foreignObject remove function",b)}});a.da.length;)try{a.da[0].close()}catch(e){I("window close function",e)}n(E,function(b){n(b.da,function(b){if(za(b,a.i))try{b.close()}catch(c){I("window close function",c)}})});a.ua=s;a.q=s;a.M=s;n(a.H,function(b,c){a.H[c]=s;delete a.H[c]});a.H=s;try{a.t.webMI=
s}catch(f){}a.i=s;a.t=s;E[b]=s;delete E[b]},Oa:function(){var a=this,b=a.t,c=a.i;if(c){var d=a.i.documentElement;a.R=b.innerHeight||d.clientHeight;a.G=b.innerWidth||d.clientWidth;c.body&&!a.G&&(a.R=c.body.clientHeight,a.G=c.body.clientWidth);1!=O(this)&&this.L();l(a.Jb,function(b){b(a.G,a.R)})}},Pa:function(a){var b=this;return function(c){if(!b.i)return s;var c=a+c,d=b.i.getElementById(c);d||(d=b.wc(c));return d}},cd:function(){return this.i.documentElement},xb:function(){return 3==O(this)?this.ia:
this.i.documentElement},Qa:function(a,b){var c=3==O(this)?new Ca:this.i.documentElement.createSVGPoint();c.x=a;c.y=b;return c},hc:function(a,b,c,d){var e=++Ib;this.H[e]={tc:a,yc:c,functionName:d,value:b};return e},Qc:function(a){this.H[a]=s;delete this.H[a]},Sb:function(a){this.$a=a;this.P=a.slice(0,4)},ya:function(a){var b=s;n(E,function(c){n(c.ua,function(c){ya(c.ba,a)&&(b=c)})});return b},pc:function(a,b,c,d,e,f,g,h,i){try{var j={z:a,element:a.create(g),id:b,x:c,y:d,width:e,height:f,parent:h,visibility:i!==
s?"hidden"!=i:s};this.q.push(j);j.z.add(j.element);ua(j.element,j.visibility);return j.element}catch(k){I("foreigenObject create function",k)}},nb:function(a,b,c,d,e,f,g,h,i){var j=this.i,k=this.ya(j);if(k===s){var n=j.createElementNS("http://www.w3.org/2000/svg","foreignObject");n.setAttribute("id",b);n.setAttribute("x",c);n.setAttribute("y",d);n.setAttribute("width",e);n.setAttribute("height",f);l(g,function(a){n.appendChild(a)});a.appendChild(n)}else{var m=tb(this.i.documentElement,a),p=this.Qa(0,
0).matrixTransform(m);h!==s&&(j=j.createElementNS("http://www.w3.org/2000/svg","rect"),j.setAttribute("transform",h),m=ub(m,j));n=this.pc(k,b,p.x+c*m.a,p.y+d*m.d,e*m.a,f*m.d,g,a,i);if(i===s)for(;a!==s&&"hasAttribute"in a;){if(a.hasAttribute("visibility")){ua(n,a.getAttribute("visibility"));break}a=a.parentNode}Ja(k,n,g)}return n},Sc:function(){for(var a=this.i.getElementsByTagNameNS("http://webmi.atvise.com/2007/svgext","foreignObject");a.length;){for(var b=a[0],c=[],d=p(b.getAttribute("x")),e=p(b.getAttribute("y")),
f=p(b.getAttribute("width")),g=p(b.getAttribute("height"));b.childNodes.length;)c.push(b.removeChild(b.childNodes[0]));this.nb(b.parentNode,b.getAttribute("id"),d,e,f,g,c,b.getAttribute("transform"),b.getAttribute("visibility"));b.parentNode.removeChild(b)}},L:function(){var a=this;if(L["frame.enableautofit"]&&!z(a.R)&&!z(a.G)){var b=a.P[0],c=a.P[1],d=a.P[2],e=a.P[3];if(a.R/e<a.G/d)var f=a.R/e,b=b-(a.G/f-d)/2;else f=a.G/d,c-=(a.R/f-e)/2}else f=1,c=b=0;d=a.i.documentElement.preserveAspectRatio;if(y(d))switch(e=
a.t.SVGPreserveAspectRatio,d.baseVal.align){case e.SVG_PRESERVEASPECTRATIO_XMINYMIN:b=c=0}a.xa=f;if(3==O(a)){var e=a.ia,d=e.coordorigin,e=e.coordsize,g=a.Q;d.x=g*b;d.y=g*c;e.x=g*a.$a[2]/f;e.y=g*a.$a[3]/f;l(a.dc,function(a){a[0].strokeweight=a[1]*f});l(a.cc,function(b){a.fc(b[0],b[1])});l(this.q,function(a){a.element.style.top=(a.top-c)*f+"px";a.element.style.left=(a.left-b)*f+"px";a.element.style.width=a.width*f+"px";a.element.style.height=a.height*f+"px"})}else l(this.q,function(a){try{a.z.set(a.element,
(a.x-b)*f,(a.y-c)*f,a.width*f,a.height*f,f)}catch(d){I("foreignObjects position function",d)}})},wc:function(a){function b(c){if(c.id==a)return c;if(c.childNodes)for(var e=0;e<c.childNodes.length;++e){var f=b(c.childNodes[e]);if(f)return f}return s}var c=s;l(this.q,function(d){d.id==a&&(c=d.element);c||(c=b(d.element))});return c},Tc:function(a,b){pa(this.ua,function(b){return b.ba==a});b===s||this.ua.push({ba:a,create:b.create,rc:b.destroy,set:b.set,add:b.add,remove:b.remove,Oc:b.register,lc:b.applyOffsetsToMatrix})},
fc:function(a,b){var c=p(b.match(/[\d\.]*/)),d=b.match(/[A-Za-z]*$/);""==b&&(c=1,d="em");isNaN(c)&&(c=1);a.style.fontSize=c*this.xa+d}});rb();window.setInterval(function(){var a=new Date-2E3;n(E,function(b,c){c&&(b.Dc<a&&!--b.Pc)&&b.rb()})},500);B(qb,{ab:function(a){var b="";l(this.i.namespaces,function(c){c.urn==a&&(b=c.name+":")});return b},createElement:function(a,b){return"createElementNS"in this.i?this.i.createElementNS(a,b):this.i.createElement(this.ab(a)+b)},createTextNode:function(a){return this.i.createTextNode(a)},
getAttribute:function(a,b,c){t(a)&&(a=this.n(a));y(a)||N();return"getAttributeNS"in a?a.getAttributeNS(b,c):a.getAttribute(this.ab(b)+c)},setAttribute:function(a,b,c,d){t(a)&&(a=this.n(a));y(a)||N();return"setAttributeNS"in a?a.setAttributeNS(b,c,d):a.setAttribute(this.ab(b)+c,d)}});var Ua={createPoint:function(a,b){return this.h.Qa(a,b)},getAttribute:function(a,b){return a.getAttribute(b)},setAttribute:function(a,b,c){return a.setAttribute(b,c)},Uc:function(a,b,c){t(a)&&(a=this.n(a));a||o("Can't find element '"+
a+"'");var d=this.h,e=p(d.w.getAttribute(a,"http://webmi.atvise.com/2007/svgext","refpx")),f=p(d.w.getAttribute(a,"http://webmi.atvise.com/2007/svgext","refpy"));if(A(a,"svg")){var g=a.parentNode;g!==s&&A(g,"g")&&(a=g)}g=a.$ID$;z(g)&&(a.$ID$=g=++this.uc);switch(b){case "Rotation":this.Va[g]=c;break;case "MoveX":this.Ta[g]=c;break;case "MoveY":this.Ua[g]=c;break;case "ScaleX":this.Wa[g]=c?c:1E-13;break;case "ScaleY":this.Xa[g]=c?c:1E-13;break;case "SkewX":this.Ya[g]=c;break;case "SkewY":this.Za[g]=
c}this.kc(a,g,d.Q,e,f,isNaN(this.Va[g])?0:this.Va[g],isNaN(this.Ta[g])?0:this.Ta[g],isNaN(this.Ua[g])?0:this.Ua[g],isNaN(this.Wa[g])?1:this.Wa[g],isNaN(this.Xa[g])?1:this.Xa[g],isNaN(this.Ya[g])?0:this.Ya[g],isNaN(this.Za[g])?0:this.Za[g],this.vc)}};l("MoveX MoveY Rotation ScaleX ScaleY SkewX SkewY".split(" "),function(a){Ua["set"+a]=function(b,c){return this.Uc(b,a,c)}});B(Y,Ua);B(Y,{addElement:function(a,b,c){var d=this.h.i.createElementNS("http://www.w3.org/2000/svg",a),e=this;n(b,function(a,b){var c=
"set"+b.substr(0,1).toUpperCase()+b.substr(1,b.length);if(c in e)e[c](d,a)});c=ma(this,c);y(c)&&c.appendChild(d);return d},getScreenCTM:function(a){z(a)?a=this.Ra:t(a)&&(a=this.n(a));var b=this.h;if("getScreenCTM"in a){if(!A(a,"svg"))return a.getScreenCTM();var b=a.appendChild(b.w.createElement("http://www.w3.org/2000/svg","g")),c=b.getScreenCTM();a.removeChild(b);return c}c=this.getScreenCTM(this.Ra);return(a=b.ya(b.i))?a.lc(c):c},addForeignObject:function(a,b){var c=this.h,b=ma(this,b),d=c.nb(b,
a.id,a.x,a.y,a.width,a.height,a.childNodes,"transform"in a?a.transform:s,"visibility"in a?a.visibility:s);c.L();return d}});var Mb={Fill:[function(a){return(a=a.getAttribute("fill"))?a.replace("url(#"+this.qa,"url(#"):a},function(a,b){t(b)&&(b=b.replace("url(#","url(#"+this.qa));return b===s?a.removeAttribute("fill"):a.setAttribute("fill",b)}],Points:[function(a){return a.points},function(a,b){if(v(b)){var c=[],d;for(d in b)v(b[d])&&2==b[d].length?c.push(b[d][0]+","+b[d][1]):y(b)?c.push(b[d].x+","+
b[d].y):c.push(b[d]);return a.setAttribute("points",c.join(" "))}}],Height:va("height"),Image:[function(a){return!a.hasAttributeNS("http://www.w3.org/1999/xlink","href")?s:a.getAttributeNS("http://www.w3.org/1999/xlink","href")},function(a,b){if(b!=s)return a.setAttributeNS("http://www.w3.org/1999/xlink","href",b)}],StrokeDasharray:[function(a){a=a.getAttribute("stroke-dasharray");t(a)&&(a=a.split(",").join(" "));return a},function(a,b){if(b===s)return a.removeAttribute("stroke-dasharray");v(b)&&
(b=b.join(","));return a.setAttribute("stroke-dasharray",b)}],Text:[function(a){return a.firstChild?a.firstChild.data:""},function(a,b){b!=s&&(a.firstChild?a.firstChild.data=b:a.appendChild(this.h.i.createTextNode(b)))}],Visible:[function(a){return"hidden"!=a.getAttribute("visibility")},function(a,b){var c=s;"http://www.w3.org/2000/svg"!=a.namespaceURI?n(this.h.q,function(b){b.element==a&&(c=b)}):(A(a,"g")||A(a,"svg"))&&n(E,function(c){var e=c.i.documentElement;l(c.q,function(c){for(var d=c.parent;d!=
e;){if(d==a){c.visibility===s&&ua(c.element,b);break}d=d.parentNode}})});if(c)ua(a,b),c.visibility=b;else if(b===s)a.removeAttribute("visibility");else return a.setAttribute("visibility",b?"visible":"hidden")}],Width:va("width"),X:va("x"),Y:va("y")};n({Circle:"circle",Ellipse:"ellipse",Group:"g",Image:"image",Line:"line",Path:"path",Polygon:"polygon",Polyline:"polyline",Rect:"rect",Text:"text"},function(a,b){Y.prototype["add"+b]=function(b,d){return this.addElement(a,b,d)}});n({X1:"x1",X2:"x2",Y1:"y1",
Y2:"y2",CenterX:"cx",CenterY:"cy",RadiusX:"rx",RadiusY:"ry",Radius:"r",FontFamily:"font-family",FontSize:"font-size",FillOpacity:"fill-opacity",FillRule:"fill-rule",PathData:"d",Stroke:"stroke",StrokeLinejoin:"stroke-linejoin",StrokeOpacity:"stroke-opacity",StrokeWidth:"stroke-width",TextAnchor:"text-anchor"},function(a,b){na(Y,b,function(b){return b.getAttribute(a)},function(b,d){return d===s?b.removeAttribute(a):b.setAttribute(a,d)})});n(Mb,function(a,b){na(Y,b,a[0],a[1])});B(W,Ua);B(W,{addElement:H(),
addForeignObject:function(a,b){var c=this.h,d=c.i,e=d.getElementById("foreignObjects"),b=ma(this,b),f=Z(b,c.Q),g=c.Qa(a.x,a.y).matrixTransform(f),h=d.createElement("div");h.style.position="absolute";c.q.push({element:h,top:g.y,left:g.x,width:a.width*f.a,height:a.height*f.d});"childNodes"in a&&(f=a.childNodes,d=c.ya(d),l(f,function(a){h.appendChild(a)}),d===s||Ja(d,h,f));c.L();return e.appendChild(h)},getScreenCTM:function(){var a=this.h,b=a.ia,c=Z(this.Ra,a.Q),d=new ba,e=a.R,a=a.G,f=p(b.style.height),
b=p(b.style.width),g=e/f,h=a/b,i=1,j=0,k=0;h<g?(i=h,k=(e-f*i)/2):(i=g,j=(a-b*i)/2);d.a=i;d.d=i;d=d.multiply(c);d.e=j+c.e*i;d.f=k+c.f*i;return d}});M.prototype.rotate=function(a,b){var c=a.x-this.x,d=a.y-this.y,e=Math.sqrt(c*c+d*d),c=Math.atan2(d,c)+b*Math.PI/180;this.x=a.x-e*Math.cos(c);this.y=a.y-e*Math.sin(c)};var Va={CenterX:[function(a,b){return(p(a.style.left)-100*b.e+p(a.style.width)/2)/(100*b.a)},function(a,b,c){a.style.left=100*b*c.a+100*c.e-p(a.style.width)/2}],CenterY:[function(a,b){return(p(a.style.top)-
100*b.f+p(a.style.height)/2)/(100*b.d)},function(a,b,c){a.style.top=100*b*c.d+100*c.f-p(a.style.height)/2}],Height:[function(a,b){var c=P(this.h,a);return c?c.height:p(a.style.height)/(100*b.d)},function(a,b,c){var d=this.h,e=P(d,a);if(e)return e.height=b,d.L();a.style.height=100*b*c.d}],Radius:[function(a,b){return p(a.style.width)/(200*b.a)},function(a,b,c){a.style.left=p(a.style.left)+(p(a.style.width)-(a.style.width=200*b*c.a))/2;a.style.top=p(a.style.top)+(p(a.style.height)-(a.style.height=200*
b*c.d))/2}],RadiusX:[function(a,b){return p(a.style.width)/(200*b.a)},function(a,b,c){a.style.left=p(a.style.left)+(p(a.style.width)-(a.style.width=200*b*c.a))/2}],RadiusY:[function(a,b){return p(a.style.height)/(200*b.d)},function(a,b,c){a.style.top=p(a.style.top)+(p(a.style.height)-(a.style.height=200*b*c.d))/2}],Width:[function(a,b){var c=P(this.h,a);return c?c.width:Math.round(p(a.style.width)/(100*b.a))},function(a,b,c){var d=this.h,e=P(d,a);if(e)return e.width=b,d.L();a.style.width=100*b*c.a}],
X:[function(a,b){var c=P(this.h,a);return c?c.left:A(a,"line")?Math.round((p(a.from.x)/100-b.e)/b.a):Math.round((p(a.style.left)/100-b.e)/b.a)},function(a,b,c){var d=this.h,e=P(d,a);if(e)return e.left=b,d.L();b=100*(b*c.a+c.e);A(a,"line")?a.from.x=b:a.style.left=b}],X1:[function(a,b){return Math.round((p(a.from.x)/100-b.e)/b.a)},function(a,b,c){a.from.x=100*(b*c.a+c.e)}],X2:[function(a,b){return Math.round((p(a.to.x)/100-b.e)/b.a)},function(a,b,c){a.to.x=100*(b*c.a+c.e)}],Y:[function(a,b){var c=P(this.h,
a);return c?c.top:A(a,"line")?Math.round((p(a.from.y)/100-b.f)/b.d):Math.round((p(a.style.top)/100-b.f)/b.d)},function(a,b,c){var d=this.h,e=P(d,a);if(e)return e.top=b,d.L();b=100*(b*c.d+c.f);A(a,"line")?(b-=600,a.from.y=b,a.to.y=b+100):a.style.top=b}],Y1:[function(a,b){return Math.round((p(a.from.y)/100-b.f)/b.d)},function(a,b,c){a.from.y=100*(b*c.d+c.f)}],Y2:[function(a,b){return Math.round((p(a.to.y)/100-b.f)/b.d)},function(a,b,c){a.to.y=100*(b*c.d+c.f)}]};n({Circle:["oval",function(a,b,c){R(a,
{fillcolor:"#000000"},{left:100*((b.centerX-b.radius)*c.a+c.e),top:100*((b.centerY-b.radius)*c.d+c.f),width:100*2*b.radius*c.a,height:100*2*b.radius*c.d})}],Ellipse:["oval",function(a,b,c){R(a,{fillcolor:"#000000"},{left:100*((b.centerX-b.radiusX)*c.a+c.e),top:100*((b.centerY-b.radiusY)*c.d+c.f),width:100*2*b.radiusX*c.a,height:100*2*b.radiusY*c.d})}],Group:["group",function(a,b,c){R(a,{coordorigin:"0,0",coordsize:"0,0"},{left:100*c.e,top:100*c.f})}],Line:["line",function(a,b,c){R(a,{from:100*(b.x1*
c.a+c.e)+","+100*(b.y1*c.d+c.f),to:100*(b.x2*c.a+c.e)+","+100*(b.y2*c.d+c.f),stroked:F},{})}],Path:["shape",function(a){var b=this.h.i;R(a,{fillcolor:"#000000",strokecolor:"#000000"},{});a.appendChild(X(b,"path",{},{}));a.appendChild(X(b,"stroke",{joinstyle:"miter"},{}))}],Polyline:["polyline",function(a,b,c){var d=[];l(b.points,function(a){v(a)&&2==a.length?d.push(100*(a[0]*c.a+c.e)+","+100*(a[1]*c.d+c.f)):y(a)?d.push(100*(a.x*c.a+c.e)+","+100*(a.y*c.d+c.f)):d.push(a)});R(a,{points:d.join(" "),fillcolor:"#000000",
strokecolor:"#000000"},{})}],Rect:["rect",function(a,b){A(a,"roundrect")&&("radiusX"in b||(b.radiusX=0),"radiusY"in b||(b.radiusY=0),0>b.radiusY&&0<=b.radiusX?b.radiusY=b.radiusX:0>b.radiusX&&0<=b.radiusY&&(b.radiusX=b.radiusY),a.$c=(b.radiusX+b.radiusY)/(2*(b.width<b.height?b.width:b.height)));R(a,{fillcolor:"#000000",stroked:F},{})}],Text:["line",function(a,b,c){var d=this.h.i;"fontSize"in b||(b.fontSize=12);b.x=100*(b.x*c.a+c.e);b.y=100*(b.y*c.d+c.f-b.fontSize/3);b.fontSize+="px";R(b,{"font-size":b.fontSize,
"font-family":"Arial"},{});a.setAttribute("from",b.x+","+b.y);a.setAttribute("to",b.x+2E5+","+(b.y+100));delete b.x;delete b.y;a.appendChild(X(d,"skew",{on:r,matrix:[c.a,0,0,c.d],origin:"-0.5,0"},{}));a.appendChild(X(d,"textpath",{on:r,string:b.text},{font:b["font-size"]+" "+b["font-family"],"v-text-align":b["v-text-align"]?b["v-text-align"]:"left"}));a.appendChild(X(d,"fill",{on:r,color:b.fill},{}));a.appendChild(X(d,"path",{textpathok:r},{}));a.appendChild(X(d,"stroke",{on:F},{}))}]},function(a,
b){W.prototype["add"+b]=function(b,d){var e=this.h,f=e.i,g=a[0];if("rect"==g&&("radiusX"in b||"radiusY"in b))g="roundrect";f=X(f,g,{},{});e=Z(d,e.Q);a[1].call(this,f,b,e);for(var h in b)if(g=h.substr(0,1).toUpperCase()+h.substr(1,h.length),g in Va)Va[g][1].call(this,f,b[h],e);else if(g="set"+g,g in this)this[g](f,b[h]);t(d)&&(d=this.n(d));y(d)&&(d.appendChild(f),Na(d));return f}});n({Fill:[function(a){return a.fillcolor},function(a,b){if(t(b)&&"url(#"==b.substr(0,5))return a.type="#"+this.qa+b.substr(5,
b.length-6);a.type="";a.filled="none"==b?F:r;return a.fillcolor=b}],FillRule:[],FontFamily:[function(a){return(a=a.getElementsByTagName("textpath")[0])?a.style.fontFamily.replace(/\'/g,""):s},function(a,b){a.getElementsByTagName("textpath")[0].style.fontFamily="'"+b+"'"}],FontSize:[function(){return 0},function(a,b){var c=this.h,d=c.cc,e=a.getElementsByTagName("textpath")[0];ga(b)&&(b+="px");var f=F;l(d,function(a){a[0]==e&&(a[1]=b,f=r)});f||d.push([e,b]);c.fc(e,b)}],PathData:[function(){o("NIY")},
function(a,b){for(var c="",d,e,f,g,h=0,i=[/(M|L)([\d\.]+),([\d\.]+)/g,/(C)([\d\.]+),([\d\.]+)\s([\d\.]+),([\d\.]+)\s([\d\.]+),([\d\.]+)/g,/(Z)/g];h<b.length;){for(var j=F,k=0;k<i.length;++k){var l=i[k].exec(b);if(l!=s){h+=l[0].length;c+=l[1].toLowerCase();for(j=2;j<l.length;++j){k=parseInt(100*l[j]);if(j%2)if(k<f||z(f))f=k;else{if(k>g||z(g))g=k}else if(k<d||z(d))d=k;else if(k>e||z(e))e=k;c+=" "+k}j=r;break}}j||o("NIY")}a.coordsize=e-d+","+(g-f);a.coordorigin=d+","+f;a.style.left=d;a.style.top=f;a.style.width=
e-d;a.style.height=g-f;(l=a.getElementsByTagName("path")[0])&&l.setAttribute("v",c);Na(a)}],Points:[function(a){return a.points},function(a,b){function c(a,b){e&&6==e.length&&(a*=e[0],b*=e[3],a+=e[4],b+=e[5]);d.push((100*a).toFixed(5)+","+(100*b).toFixed(5))}if(v(b)){var d=[],e=this.h.w.getAttribute(a,"http://webmi.atvise.com/2007/svgext","matrix");if(e&&""!=e&&(e=e.split(","),6==e.length))for(var f in e)e[f]=p(e[f]);for(f in b)v(b[f])&&2==b[f].length?c(b[f][0],b[f][1]):y(b)?c(b[f].x,b[f].y):d.push(b[f]);
return a.points.value=d.join(",")}}],Stroke:[function(a){return a.strokecolor},function(a,b){if("url(#"==b.substr(0,5))return a.type=b.substr(0,b.length-1).replace("url(#","#"+this.qa);a.stroked="none"==b?F:r;return a.strokecolor=b}],StrokeWidth:[function(a){return a.strokeweight/0.75/this.h.xa},function(a,b){var b=0.75*b,c=this.h,d=c.dc,e=F;l(d,function(c){c[0]==a&&(c[1]=b,e=r)});e||d.push([a,b]);a.strokeweight=b*c.xa}],TextAnchor:[function(a){a=a.getElementsByTagName("textpath")[0];return!a?s:a.style["v-text-align"]},
function(a,b){var c=0,d=1,e=a.getElementsByTagName("textpath"),f=String(a.from).split(","),g=String(a.to).split(",");"middle"==b?(b="center",c=-0.5,d=0.5):"right"==b&&(c=-1,d=0);a.from=p(f[0])+2E5*c+","+f[1];a.to=p(g[0])-2E5+2E5*d+","+g[1];e[0].style["v-text-align"]=b}],Visible:[function(a){return"hidden"!=a.style.visibility},function(a,b){return b===s?a.style.visibility="":a.style.visibility=b?"visible":"hidden"}]},function(a,b){na(W,b,a[0],a[1])});n(Va,function(a,b){na(W,b,function(b){return a[0].call(this,
b,Z(b.parentNode,this.h.Q))},function(b,d){return a[1].call(this,b,d,Z(b.parentNode,this.h.Q))})});n({FillOpacity:["fill","opacity",0,1],Image:["imagedata","src"],StrokeDasharray:["stroke","dashstyle"],StrokeLinejoin:["stroke","joinstyle"],StrokeOpacity:["stroke","opacity",0,1],Text:["textpath","string"]},function(a,b){var c=a[0],d=a[1];na(W,b,function(a){a=a.getElementsByTagName(c);if(a.length)return a[0][d]},function(b,f){f==s&&(f="");2<a.length&&(f<a[2]&&(f=a[2]),f>a[3]&&(f=a[3]));var g=b.getElementsByTagName(c);
g.length||(g=this.h.i.createElement("v:"+c),b.appendChild(g),g=[g]);for(var h=0;h<g.length;++h)g[h][d]=f})});B(La,{connect:function(a,b,c){var c=t(c)&&c.length?this.aa+c:this.aa.substr(0,this.aa.length-1),d=this.h.M;d&&(a in d?c in d[a]?d[a][c].push(b):d[a][c]=[b]:(d[a]={})[c]=[b])},fire:function(a,b,c){function d(a){var c={value:b};l(a,function(a){a(c)})}var e=this;if(v(a))l(a,function(a,d){e.fire(a,v(b)?b[d]:b,v(c)?c[d]:c)});else if(t(c)){if(e.h.M&&a in e.h.M){var c=c.length?this.aa+c:this.aa.substr(0,
this.aa.length-1),f=e.h.M[a];c in f&&d(f[c])}}else n(E,function(b){b.M&&a in b.M&&n(b.M[a],d)})}});B(vb,{isChecked:function(a){return this.n(a).checked},setChecked:function(a,b){this.n(a).checked=b?r:F}});B(wb,{addItem:function(a,b,c){var a=this.n(a),d=a.ownerDocument;try{var e=d.createElementNS("http://www.w3.org/1999/xhtml","option")}catch(f){e=d.createElement("option")}e.value=z(c)?b:c;return a.appendChild(e).appendChild(d.createTextNode(b))},setItems:function(a,b){for(var c=this,d=this.n(a);d.childNodes.length;)d.removeChild(d.childNodes[0]);
v(b)?l(b,function(b){c.addItem(a,b)}):n(b,function(b,d){c.addItem(a,b,d)})}});B(Ma,{getDisabled:function(a){return this.n(a).disabled},setDisabled:function(a,b){this.n(a).disabled=b?r:F},getValue:function(a){return this.n(a).value},setValue:function(a,b){this.n(a).value=b}});B(Ka,{addOnfocus:function(a){this.h.ic(a)},addOnload:function(a){this.h.ob(a)},addOnresize:function(a){this.h.pb(a)},addOnunload:function(a){this.h.jc(a)},getConfig:function(a){return L[a]},setConfig:function(a,b){if(z(a)||typeof L[a]!=
typeof b)return F;L[a]=b;return r},hasRight:function(a){return"right"in oa&&S(a,oa.right)},setExtension:function(a,b,c){Aa[a]=[{},b,c]},inList:S,sprintf:Za,translate:Ya,proxy:function(a,b){b||(b=window);var c=b.document,d=s,e=b.webMI;z(e)&&(ab(b),b.webMI=e=new Ka(b,r));n(E,function(a){n(a.da,function(a){try{za(a,c)&&(b.close=function(){a.close()})}catch(d){}})});if(a!==s){var f=function(f){function h(f,g,i,j,k,l){var p=a[f],t=p[0],u={};p[3]&&i in p[3]&&(k=aa(k,p[3][i]));n(k,function(a,b){function c(b){var d=
l.webMI.query;return b in a&&a[b]in d?d[a[b]]:""}if(y(a)){var d={a:c("a"),b:c("b"),v:a.v};u[b]=d.b+("v"in a?d.v:"")+d.a;y(d.a)&&(u[b]=d.a);y(d.b)&&(u[b]=d.b);y(d.v)&&(u[b]=d.v)}else u[b]=a});var v=new Hb(b,e,f,g,j,aa(p[2],u),l);n(p[1],function(a,b){h(a[0],c.getElementById(j+b),j+b,j+b+"_",a[1],v.jb)});try{t(v.Yb,v.jb,v.Xb,v.jb)}catch(x){d||(d=x)}}var i=e.h.xb(),j=e.h.w;if(j!==s){if(j=j.getAttribute(i,"http://webmi.atvise.com/2007/svgext","oe")){var k=parseInt(j.substr(0,1)),p=0;l(j.substr(1),function(a,
b){p=(p<<4)+x.indexOf(a)-parseInt(f.substr(b%f.length,1),16);if(b%k==k-1){var d=c.getElementById("id_"+p);d&&d.parentNode.removeChild(d);p=0}});e.gfx.setVisible(i,s)}h("",i,"","",e.query,b);d&&o(d)}};t(U)?f(U):U.push(f)}},runInterval:function(a,b,c){for(var d=0;d<b;++d)this.h.t.setTimeout(c,(d+1)*a,d)},setInterval:function(a,b){return this.h.t.setInterval(b,a)}});return new Ka(window)}());
